[tools]
go = "1.25.11"
pre-commit = "4.6.0"
golangci-lint = "2.12.2"
gotestsum = "1.13.0"
node = "26.1.0"

[tasks.fmt]
description = "Format project"
dir = "src"
run = ["gofmt -w .", "go mod tidy"]

[tasks.fix]
description = "Auto fix lint issues"
dir = "src"
run = ["golangci-lint run --fix ./..."]

[tasks.bundle-swagger]
description = "Bundle swagger"
run = "npx openapi-merger -i src/api/docs/main.yaml -o src/api/docs/openapi.yaml"


[tasks.lint]
description = "Run linters"
dir = "src"
run = ["golangci-lint run ./..."]

[tasks.vet]
description = "Run go vet"
run = ["go vet ./..."]

[tasks.build]
description = "Build project"
run = ["go build ./..."]

[tasks.test]
description = "Run tests"
run = ["gotestsum --format=testname -- -count=1 ./..."]

[tasks.test-race]
description = "Run race tests"
run = ["gotestsum --format=testname -- -race -count=1 ./..."]

[tasks.coverage]
description = "Generate HTML coverage"
run = [
  "mkdir -p .coverage",
  "gotestsum --format=testname --junitfile=.coverage/junit.xml -- -covermode=atomic -coverprofile=.coverage/coverage.out ./...",
  "go tool cover -html=.coverage/coverage.out -o .coverage/coverage.html",
]

[tasks.clean]
description = "Clean caches"
run = ["go clean -cache -testcache -modcache", "rm -rf .coverage"]

[tasks.check]
description = "Checks"
depends = ["fmt", "vet", "lint", "test"]

[tasks.complete-check]
description = "Complete Checks"
depends = ["fmt", "vet", "lint", "test-race", "coverage"]

[tasks.deps]
description = "Update dependencies"
run = ["go get -u ./...", "go mod tidy"]

[tasks.bench]
description = "Run benchmarks"
run = ["go test -bench=. ./..."]
