openapi: 3.1.1
info:
  title: Sample
  description: API for Sample application
  version: "1.0"
  contact:
    email: erfan.ehsany@outlook.com

servers:
  - url: http://127.0.0.1:8000
  - url: http://localhost:8000

tags:
  - name: common
    description: common web services

  - name: user
    description: user web services

security:
  - BearerAuth: []

paths:
  # common services


  # login services
  /api/v1/user/login:
    post:
      summary: login service
      description: Returns jwt for user login
      security: []

      tags:
        - user

      parameters:
        - $ref: "#/components/parameters/LanguageHeader"
        - $ref: "#/components/parameters/RequestIdHeader"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"

      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

  # user crud
  /api/v1/user:
    # list
    get:
      summary: get users
      description: Returns users list
      security: []

      tags:
        - user

      parameters:
        - $ref: "#/components/parameters/LanguageHeader"
        - $ref: "#/components/parameters/RequestIdHeader"
        - $ref: "#/components/parameters/LimitPaginationQuery"
        - $ref: "#/components/parameters/OffsetPaginationQuery"
        - $ref: "#/components/parameters/FilterPaginationQuery"

      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersPaginatedResponse"

    # create
    post:
      summary: Create a new user
      description: Create a new user with provided data
      security: []
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersDetailCreateResponse"

  /api/v1/user/{id}:
    # detail
    get:
      summary: get user detail
      description: Returns user detail
      security: []

      tags:
        - user

      parameters:
        - $ref: "#/components/parameters/UrlDetail"
        - $ref: "#/components/parameters/LanguageHeader"
        - $ref: "#/components/parameters/RequestIdHeader"

      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersDetailResponse"

    # update
    put:
      summary: Update an existing user
      description: Update user data partially or fully
      security: []
      tags:
        - user
      parameters:
        - $ref: "#/components/parameters/UrlDetail"
        - $ref: "#/components/parameters/LanguageHeader"
        - $ref: "#/components/parameters/RequestIdHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "204":
          $ref: "#/components/schemas/UpdateResponse"


    # delete
    delete:
      summary: Delete a user
      description: Soft-delete a user by ID
      security: []
      tags:
        - user
      parameters:
        - $ref: "#/components/parameters/UrlDetail"
        - $ref: "#/components/parameters/LanguageHeader"
        - $ref: "#/components/parameters/RequestIdHeader"
      responses:
        "204":
          $ref: "#/components/schemas/DeleteResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    $ref: "./base/parameters.yaml"

  schemas:
    # standard response
    StandardResponse:
      type: object
      properties:
        result:
          nullable: true
        error:
          nullable: true
          type: string
        success:
          type: boolean
        code:
          type: integer
          format: int32

    # responses
    UpdateResponse:
      description: "Updated"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "No content"
            success: false
            code: 204

    DeleteResponse:
      description: "Deleted"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "No content"
            success: false
            code: 204

    "400":
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "Bad request"
            success: false
            code: 400

    "401":
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "invalid or expired token"
            success: false
            code: 401

    "403":
      description: "Forbidden"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "permission denied"
            success: false
            code: 403

    "404":
      description: "Not Found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "entity not found"
            success: false
            code: 404

    "422":
      description: "Unprocessable input"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StandardResponse"
          example:
            result: null
            error: "unprocessable input"
            success: false
            code: 422

    # USER LOGIN
