UrlDetail:
  name: id
  in: path
  required: true
  schema:
    type: integer
    format: uint64

LanguageHeader:
  name: "Accept-Language"
  in: header
  description: "user selected language"
  required: false
  schema:
    type: string
    enum:
      - en
      - fa
    example: fa

RequestIdHeader:
  name: "X-Request-ID"
  in: header
  description: request reference
  required: false
  schema:
    type: string

LimitPaginationQuery:
  name: limit
  in: query
  description: Maximum number of results to return
  required: false
  schema:
    type: integer
    default: 20

OffsetPaginationQuery:
  name: offset
  in: query
  description: Number of items to skip
  required: false
  schema:
    type: integer
    default: 0

    FilterPaginationQuery:
      name: filters
      in: query
      description: Filters in dynamic form
      required: false
      style: form
      explode: false

      schema:
        type: array
        items:
          type: object
          properties:
            field:
              type: string
            operator:
              type: string
              enum: [eq, like, gt, gte, lt, lte]
            value:
              oneOf:
                - type: string
                - type: number
                - type: boolean
                - type: string
                  format: date-time
