// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapper

import (
	dto "sample/src/pkg/dto"
	entities "sample/src/pkg/entities"
)

type UserConverterImpl struct{}

func (c *UserConverterImpl) ToDetail(source *entities.User) *dto.UserDetail {
	var pDtoUserDetail *dto.UserDetail
	if source != nil {
		var dtoUserDetail dto.UserDetail
		dtoUserDetail.ID = (*source).BaseModel.ID
		dtoUserDetail.Mobile = (*source).Mobile
		dtoUserDetail.Email = (*source).Email
		dtoUserDetail.NationalCode = NullStringToPtr((*source).NationalCode)
		dtoUserDetail.BirthDate = NullTimeToPtr((*source).BirthDate)
		dtoUserDetail.CreatedAt = TimeToTime((*source).BaseModel.CreatedAt)
		dtoUserDetail.UpdatedAt = TimeToTime((*source).BaseModel.UpdatedAt)
		dtoUserDetail.DeletedAt = GormDeletedAtToPtr((*source).BaseModel.DeletedAt)
		dtoUserDetail.Permissions = PermissionsToNames((*source).Permissions)
		pDtoUserDetail = &dtoUserDetail
	}
	return pDtoUserDetail
}
func (c *UserConverterImpl) ToEntity(source *dto.CreateUser) *entities.User {
	var pEntitiesUser *entities.User
	if source != nil {
		var entitiesUser entities.User
		entitiesUser.Mobile = (*source).Mobile
		entitiesUser.Email = (*source).Email
		entitiesUser.NationalCode = PtrToNullString((*source).NationalCode)
		entitiesUser.BirthDate = PtrToNullTime((*source).BirthDate)
		pEntitiesUser = &entitiesUser
	}
	return pEntitiesUser
}
func (c *UserConverterImpl) ToList(source *entities.User) *dto.UserInfo {
	var pDtoUserInfo *dto.UserInfo
	if source != nil {
		var dtoUserInfo dto.UserInfo
		dtoUserInfo.ID = (*source).BaseModel.ID
		dtoUserInfo.Mobile = (*source).Mobile
		dtoUserInfo.Email = (*source).Email
		dtoUserInfo.NationalCode = NullStringToPtr((*source).NationalCode)
		dtoUserInfo.BirthDate = NullTimeToPtr((*source).BirthDate)
		dtoUserInfo.Permissions = PermissionsToNames((*source).Permissions)
		pDtoUserInfo = &dtoUserInfo
	}
	return pDtoUserInfo
}
func (c *UserConverterImpl) ToListSlice(source []*entities.User) []*dto.UserInfo {
	var pDtoUserInfoList []*dto.UserInfo
	if source != nil {
		pDtoUserInfoList = make([]*dto.UserInfo, len(source))
		for i := 0; i < len(source); i++ {
			pDtoUserInfoList[i] = c.ToList(source[i])
		}
	}
	return pDtoUserInfoList
}
func (c *UserConverterImpl) ToUpdateEntity(source *dto.UpdateUser) *entities.User {
	var pEntitiesUser *entities.User
	if source != nil {
		var entitiesUser entities.User
		entitiesUser.Email = PtrToString((*source).Email)
		entitiesUser.Password = PtrToString((*source).Password)
		entitiesUser.NationalCode = PtrToNullString((*source).NationalCode)
		entitiesUser.BirthDate = PtrToNullTime((*source).BirthDate)
		pEntitiesUser = &entitiesUser
	}
	return pEntitiesUser
}
